name: BUILD AND PUBLISH

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "build"
        with:
          package-manager: npm
          command: ts:build
